import { User } from '@/app/@types/user'

export const users: User[] = [
  {
    createdAt: '2025-02-26T08:07:27.137Z',
    name: 'Angelina Hilll',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/676.jpg',
    country: 'Kyrgyz Republic',
    city: 'North Dominique',
    company: 'Windler - Dickinson',
    job: 'Principal Web Specialist',
    account: '94097067',
    mother: 'Oliver Jacobs',
    id: '3',
  },
  {
    createdAt: '2025-02-26T11:50:04.573Z',
    name: 'Christina Feeney',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/838.jpg',
    country: 'Timor-Leste',
    city: 'Audrafort',
    company: 'Parker, Boehm and Dickens',
    job: 'District Metrics Liaison',
    account: '08761910',
    mother: 'Courtney Brakus',
    id: '4',
  },
  {
    createdAt: '2025-02-25T15:04:39.631Z',
    name: 'Micheal Altenwerth',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/850.jpg',
    country: 'Bulgaria',
    city: 'Orange',
    company: 'Kihn - Fadel',
    job: 'National Interactions Consultant',
    account: '33828181',
    mother: 'Michelle Jacobi DDS',
    id: '5',
  },
  {
    createdAt: '2025-02-26T09:52:31.386Z',
    name: 'Darren Moen',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/114.jpg',
    country: 'Niger',
    city: 'Santa Monica',
    company: 'Kulas, Hackett and Stiedemann',
    job: 'Legacy Directives Agent',
    account: '96242724',
    mother: 'Kerry Bailey',
    id: '6',
  },
  {
    createdAt: '2025-02-26T06:03:27.732Z',
    name: 'Darren Runolfsdottir',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1229.jpg',
    country: 'Mongolia',
    city: 'Loyalbury',
    company: 'Quitzon Inc',
    job: 'Product Usability Orchestrator',
    account: '33482678',
    mother: 'Esther Brakus',
    id: '7',
  },
  {
    createdAt: '2025-02-26T02:56:04.086Z',
    name: 'Jaime Tromp',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/355.jpg',
    country: 'Pakistan',
    city: 'Lake Murielbury',
    company: 'Goyette LLC',
    job: 'Direct Configuration Agent',
    account: '58500712',
    mother: 'Dr. Christine Bahringer',
    id: '8',
  },
  {
    createdAt: '2025-02-26T07:10:48.348Z',
    name: 'Glenda Klocko Jr.',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/315.jpg',
    country: 'Azerbaijan',
    city: 'Owentown',
    company: 'Langworth, Balistreri and Howe',
    job: 'Customer Interactions Technician',
    account: '73062968',
    mother: 'Jim Koepp',
    id: '9',
  },
  {
    createdAt: '2025-02-26T11:34:38.584Z',
    name: 'Tom Crooks',
    avatar:
      'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/968.jpg',
    country: 'Cambodia',
    city: 'Missouri City',
    company: 'Cremin - Wolf',
    job: 'Product Research Analyst',
    account: '85068060',
    mother: 'Brandy Turner',
    id: '10',
  },
]
